# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage:
     job:
      - job
        steps: 
        - script: pdw
        displayName:'Mostrar en donde estoy cuando ejecuto el pipeline'

        - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
          displayName: 'Show file in machine'
